# Where the next timer timestamp is saved, so that the timestamp is preserved across reboots
TimestampFile = 'next_execution_timestamp'

# Where the stories are saved
BaseFolder = '/home/user/instagram_stories/'
FeedFolder = 'home/user/instagram_feeds/'

FolderFormat = 1


# Fairly obvious
[Instagram]
Username = 'Username'
Password = 'Password'

[Targets]
# Usernames of targets
targets = ['foo', 'bar', 'baz']

# username of target
[FeedTarget]
target = ''
